language: node_js
node_js:
  - lts/*
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE houseHunting;" -U postgres

  - 'npm run build:db'
env:
  global:
    - PGPORT=5432
test:
  adapter: postgresql
  database: houseHunting

  